<a href="https://colab.research.google.com/github/sudeltas/Math-2024-25-Winter/blob/main/LA_Matrix_basic_operations_en.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Define matrices
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# 1. Matrix Addition
C = A + B
print("A + B:\n", C)

# 2. Matrix Subtraction
D = A - B
print("\nA - B:\n", D)

# 3. Matrix Multiplication
E = np.dot(A, B)
print("\nA * B:\n", E)

# 4. Transpose
F = A.T
print("\nA Transpose:\n", F)

# 5. Determinant Calculation
det_A = np.linalg.det(A)
print("\nDeterminant of A:", det_A)

# 6. Inverse Calculation
try:
    inv_A = np.linalg.inv(A)
    print("\nInverse of A:\n", inv_A)
except np.linalg.LinAlgError:
    print("\nA matrix is not invertible.")

# 7. Eigenvalues and Eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
print("\nEigenvalues of A:", eigenvalues)
print("Eigenvectors of A:\n", eigenvectors)


A + B:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]

A - B:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

A * B:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

A Transpose:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]

Determinant of A: 0.0

A matrix is not invertible.

Eigenvalues of A: [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
Eigenvectors of A:
 [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]
